baseurl = "/"
title = "Mark's Blog"
languageCode = "en-us"
pagination.pagerSize = 10 # Number of posts per page
theme = "mainroad"
ignorefiles = [ "index.md" ]

[Params]
  description = "Mark's Blog" # Description of your site
  opengraph = false
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = false
  pager = false
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post"]
  # mainSections = ["post", "docs"]

[Params.Author]
  name = "Mark"
  bio = "Mark is a guy who does things."
  # avatar = "img/avatar.png"

[Params.logo]
  subtitle = "Tech + Family Stuff" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
