baseURL = "https://pukkachomby.github.io"
languageCode = "en-us"
title = "Blog"
theme = "yinyang"
DefaultContentLanguage = "en"

[author]
  name = "Mark"
  homepage = "https://pukkachomby.github.io/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

[params]
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "Mark's Blog"
